my_project/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story5.urls'))
]

story5/urls.py
from django.urls import path

from . import views
from .views import index, add_course, course_details, delete_course


app_name = "story5"

urlpatterns = [
    path("", views.index, name="index"),
    path("add/", views.add_course, name="add_course"),
    path("details/<int:pk>", views.course_details, name="course_details"),
    path("delete/<int:pk>", views.delete_course, name="delete_course")
]

story5/models.py
from django.db import models
from django.shortcuts import reverse


class Course(models.Model):
    name = models.CharField(max_length=70)
    lecturer = models.CharField(max_length=70)
    sks = models.PositiveIntegerField()
    TERM_CHOICES = [
    ('Odd', 'Odd'),
    ('Even', 'Even')
    ]
    YEAR_CHOICES = [
    ('2020/2021', '2020/2021'),
    ('2021/2022', '2021/2022'),
    ('2022/2023', '2022/2023'),
    ('2023/2024', '2023/2024')
    ]
    term = models.CharField(
        max_length=4, 
        choices= TERM_CHOICES,
        default= 'Odd')
    year = models.CharField(
        max_length=9,
        choices= YEAR_CHOICES,
        default='2020/2021'
    )
    room = models.CharField(max_length=30)
    desc = models.CharField(max_length=1000)

    def __str__(self):
        return self.name

story5/forms.py
from django import forms

from .models import Course


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['name', 'lecturer', 'sks', 'term', 'year', 'room', 'desc']
        widgets = {
            'name' : forms.TextInput(attrs={'class': 'form-control'}),
            'lecturer' : forms.TextInput(attrs={'class': 'form-control'}),
            'sks' : forms.NumberInput(attrs={'class': 'form-control'}),
            'term' : forms.Select(attrs={'class': 'form-control'}),
            'year' : forms.Select(attrs={'class': 'form-control'}),
            'room' : forms.TextInput(attrs={'class': 'form-control'}),
            'desc' : forms.Textarea(attrs={'class': 'form-control'}),
        }

story5/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

from .forms import CourseForm
from .models import Course


def index(request):
    courses = Course.objects.all()
    empty = False
    if not courses:
        empty = True
    context = {'courses': courses, 'empty': empty}
    return render(request, 'story5/index.html', context)

def add_course(request):
    form = CourseForm()
    if request.method == "POST":
        form = CourseForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, (f"{request.POST['name']} course added."))
        return redirect('story5:index')
    context = {'form' : form}
    return render(request, 'story5/add.html', context)

def course_details(request, pk):
    course = Course.objects.get(id=pk)
    context = {'course': course}
    return render(request, 'story5/details.html', context)

def delete_course(request, pk):
    if request.method == "POST":
        course = Course.objects.get(id=pk)
        course.delete()
        messages.success(request, (f"{course} course deleted."))
    return redirect('story5:index')

story5/templates/story5/add.html
{% extends 'story5/base.html' %}
{% block content %}
<div class="container">
    <form class="mt-5" method="POST">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-6">
                <label>Course Name</label>
                {{ form.name }}
            </div>
            <div class="form-group col-md-3">
                <label>Term</label>
                {{ form.term }}
            </div>
            <div class="form-group col-md-3">
                <label>Academic Year</label>
                {{ form.year }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label>Lecturer</label>
                {{ form.lecturer }}
            </div>
            <div class="form-group col-md-3">
                <label>Room</label>
                {{ form.room }}
            </div>
            <div class="form-group col-md-3">
                <label>Credit (SKS)</label>
                {{ form.sks }}
            </div>
        </div>
        <div class="form-group">
            <label>Description</label>
            {{ form.desc }}
        </div>
        <button type="submit" class="btn btn-primary">Add</button>
    </form>
</div>
{% endblock content %}

story5/templates/story5/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Primary Meta Tags -->
    <title>COOLYEAH - College Course Organizer</title>
    <meta name="title" content="COOLYEAH">
    <meta name="description" content="A college course organizer to save yourselves from headache!">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://jojostory5.herokuapp.com/">
    <meta property="og:title" content="COOLYEAH">
    <meta property="og:description" content="A college course organizer to save yourselves from headache!">

    <!-- Bootstrap CSS and Scripts -->
    <link rel="stylesheet" href="{% static 'story5/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light navbar-custom justify-content-between">
        <a class="navbar-brand" href="/">COOLYEAH</a>
        <a href="{% url 'story5:add_course' %}" class="btn btn-primary">Add Course</a>
    </nav>

    {% block content %}
    {% endblock %}

    <footer class="page-footer font-small fixed-bottom">
        <div class="footer-copyright text-center py-3">
            Made by Jojo, 2020
        </div>
    </footer>
</body>
</html>

story5/templates/story5/details.html
{% extends 'story5/base.html' %}
{% block content %}
<div class="container my-4">
    <div class="jumbotron">
        <h1 class="display-4">{{ course.name }}</h1>
        <p class="lead">{{ course.term }} {{ course.year }}</p>
        <p>{{ course.desc }}</p>
        <hr class="my-4">
        <table class="table w-auto">
            <tbody>
                <tr>
                    <th>Lecturer</th>
                    <td><span class="badge badge-light">{{ course.lecturer }}</span></td>
                </tr>
                <tr>
                    <th>SKS</th>
                    <td><span class="badge badge-light">{{ course.sks }}</span></td>
                </tr>
                <tr>
                    <th>Room</th>
                    <td><span class="badge badge-light">{{ course.room }}</span></td>
                </tr>
            </tbody>
        </table>
        <a class="btn btn-outline-primary mt-4" href="{% url 'story5:index' %}" role="button">BACK</a>
    </div>
</div>
{% endblock content %}

story5/templates/story5/index.html
{% extends 'story5/base.html' %}
{% load static %}
{% block content %}
<div class="container my-4">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissible fade show mt-4" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}
    {% for course in courses %}
        <div class="card mt-3">
            <div class="card-body d-flex justify-content-between flex-column flex-md-row">
                <div>
                    <a href="{% url 'story5:course_details' course.id %}">
                        <h5 class="card-title">{{ course.name }}</h5>
                    </a>
                    <h6 class="card-subtitle mb-2 text-muted">{{ course.term }} {{ course.year }}</h6>
                </div>
                <form action="{% url 'story5:delete_course' course.id %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-danger card-link mt-2 mr-md-4 align-self-center" type="input">
                        DELETE
                    </button>
                </form>    
            </div>
        </div>
    {% endfor %}
    {% if empty %}
        <div class="container d-flex h-100">
            <div class="row align-self-center w-100">
                <div class="col-lg-4 col-md-6 col-sm-6 mx-auto">
                    <div class="container" align="center">
                        <img src="{% static 'story5/images/fubuki.jpg' %}" class="img-fluid" alt="hamburger yum" id="fubuki">
                        <h3>Course Empty</h3>
                        <p class="lead">Add a course and it will show up here.</p>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
</div>
{% endblock %}